DROP DATABASE IF EXISTS lapoupee;

CREATE DATABASE IF NOT EXISTS lapoupee;
USE lapoupee;

DROP TABLE IF EXISTS GOODS;
DROP TABLE IF EXISTS CUSTOMER_INFO;
DROP TABLE IF EXISTS ORDER_INFO;
DROP TABLE IF EXISTS CART;


CREATE TABLE IF NOT EXISTS GOODS(
GOODS_ID INT(10) AUTO_INCREMENT,
GOODS_NAME VARCHAR(100) NOT NULL,
STOCK INT(4),
UNIT_PRICE INT(10),
PRIMARY KEY(GOODS_ID)
);


CREATE TABLE IF NOT EXISTS CUSTOMER_INFO(
CUSTOMER_ID INT(10)  AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(50) NOT NULL,
CUSTOMER_PASS VARCHAR(25) UNIQUE NOT NULL,
MAILADDRESS  VARCHAR(50) NOT NULL,
POSTCODE  VARCHAR(7) NOT NULL,
ADDRESS  VARCHAR(100) NOT NULL,
TELLNUMBER VARCHAR(12) NOT NULL,
REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(CUSTOMER_ID)
);


CREATE TABLE IF NOT EXISTS ORDER_INFO(
CUSTOMER_ID INT(10) NOT NULL,
GOODS_ID INT(10) NOT NULL,
ORDER_QUANTITY INT(3) NOT NULL,
TOTAL_AMOUNT INT(10) NOT NULL,
PAY_MATHOD INT(1) NOT NULL,
CREDIT_COMPAN INT(1) NOT NULL, 
CREDIT_NUMBER INT(16) NOT NULL,
CON_SET INT(1) NOT NULL,
BANK_SET INT(1) NOT NULL,
PURCHASEDAY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_INFO(CUSTOMER_ID),
FOREIGN KEY(GOODS_ID) REFERENCES GOODS(GOODS_ID)
);

CREATE TABLE IF NOT EXISTS CART(
TEMPORARY_ID VARCHAR(50) NOT NULL,
GOODS_NAME VARCHAR(100) NOT NULL,
SALES_COUNT INT(10) NOT NULL,
UNIT_PRICE INT(10) NOT NULL,
TOTAL_AMOUNT INT(10) NOT NULL
);

